package edtech.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AsciidocSlideAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAsciidocSlideAllPropertiesEquals(AsciidocSlide expected, AsciidocSlide actual) {
        assertAsciidocSlideAutoGeneratedPropertiesEquals(expected, actual);
        assertAsciidocSlideAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAsciidocSlideAllUpdatablePropertiesEquals(AsciidocSlide expected, AsciidocSlide actual) {
        assertAsciidocSlideUpdatableFieldsEquals(expected, actual);
        assertAsciidocSlideUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAsciidocSlideAutoGeneratedPropertiesEquals(AsciidocSlide expected, AsciidocSlide actual) {
        assertThat(actual)
            .as("Verify AsciidocSlide auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAsciidocSlideUpdatableFieldsEquals(AsciidocSlide expected, AsciidocSlide actual) {
        assertThat(actual)
            .as("Verify AsciidocSlide relevant properties")
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getContent()).as("check content").isEqualTo(expected.getContent()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()))
            .satisfies(a -> assertThat(a.getNum()).as("check num").isEqualTo(expected.getNum()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAsciidocSlideUpdatableRelationshipsEquals(AsciidocSlide expected, AsciidocSlide actual) {
        assertThat(actual)
            .as("Verify AsciidocSlide relationships")
            .satisfies(a -> assertThat(a.getPresentation()).as("check presentation").isEqualTo(expected.getPresentation()));
    }
}
