package edtech.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ImageResourceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImageResourceAllPropertiesEquals(ImageResource expected, ImageResource actual) {
        assertImageResourceAutoGeneratedPropertiesEquals(expected, actual);
        assertImageResourceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImageResourceAllUpdatablePropertiesEquals(ImageResource expected, ImageResource actual) {
        assertImageResourceUpdatableFieldsEquals(expected, actual);
        assertImageResourceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImageResourceAutoGeneratedPropertiesEquals(ImageResource expected, ImageResource actual) {
        assertThat(actual)
            .as("Verify ImageResource auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImageResourceUpdatableFieldsEquals(ImageResource expected, ImageResource actual) {
        assertThat(actual)
            .as("Verify ImageResource relevant properties")
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getUri()).as("check uri").isEqualTo(expected.getUri()))
            .satisfies(a -> assertThat(a.getResolution()).as("check resolution").isEqualTo(expected.getResolution()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImageResourceUpdatableRelationshipsEquals(ImageResource expected, ImageResource actual) {
        assertThat(actual)
            .as("Verify ImageResource relationships")
            .satisfies(a -> assertThat(a.getAsciidocSlide()).as("check asciidocSlide").isEqualTo(expected.getAsciidocSlide()));
    }
}
