@startuml

skinparam noteBackgroundColor #FFFFCC
skinparam noteBorderColor #000000
skinparam ObjectFontSize 20

object User {
  id: Long
  email: String
  login: String
}

object Workspace {
  user: User
  presentations: List<Presentation>
}

object Presentation {
  workspace: Workspace
  plan: String
  uri: String
  slides: List<AsciiDoc>
}
note right of Presentation
  **Représente la présentation dans son intégralité.**
  - Contient une liste d'objets `Slide`.
  - `plan` fournit un aperçu de la structure.
  - C'est le résultat final généré à partir du `AsciiDoc`.
end note

object Site {
  workspace: Workspace
  plan: String
  uri: String
  articles: List<AsciiDocArticle>
}
note right of Site
  **Représente la présentation dans son intégralité.**
  - Contient une liste d'objets `Slide`.
  - `plan` fournit un aperçu de la structure.
  - C'est le résultat final généré à partir du `AsciiDoc`.
end note

object Training {
  workspace: Workspace
}
note right of Training
  **Représente le training dans son intégralité.**
end note

object School {
  workspace: Workspace
  trainings: List<Training>
}
note right of School
  **Représente une école dans son intégralité.**
  - liste des formations.
end note

User "1" - "1" Workspace : "owns"
Workspace "1" *--- "0..*" Presentation : "generates"
Workspace "1" *-- "0..*" Site : "generates"
Workspace "1" *--- "0..*" Training : "generates"
Workspace "1" *-- "0..*" School : "generates"

@enduml
